title: Nasma Al-Shutfa
nav:
  - label: I am grateful(?)
    url: /content/projects/2025-11-i-am-grateful/
  - label: About/Contact
    url: /#about
footer:
  text: Get in touch
  links:
    - label: Email
      url: mailto:example@example.com
    - label: Instagram
      url: https://instagram.com/example-user
  info: © 2025 Nasma. All rights reserved.
